map_type: costmap

obstacle_range: 1.5
raytrace_range: 2.0

transform_tolerance: 0.3

inflation_radius: 1.70
robot_radius : 0.3
observation_sources: laser_scan_sensor
cost_scaling_factor : 2.50
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
